name: Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
     #name: Build the Docker image
     # run: docker-compose -f Pokedex/docker-compose.yml build
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: docker-compose -f Pokedex/docker-compose.yml build
          
          #run: docker-compose -f Pokedex/docker-compose.yml build
          
          # Note: tags has to be all lower-case
          tags: |
            schen21/pokedexapi:pokedexapi-latest 
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}

